- name: Deploy edX Ecommerce Worker
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_DATADOG: False
    ENABLE_NEWRELIC: False
  roles:
    - aws
    - ecomworker
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic_infrastructure
      when: COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE
    - role: datadog-uninstall
      when: not COMMON_ENABLE_DATADOG
    - role: hermes
      hermes_service_config: "{{ ECOMMERCE_WORKER_HERMES_SERVICE_CONFIG }}"
      when: ECOMMERCE_WORKER_ENABLE_HERMES

